[package]
name = "jobs-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace
result = { workspace = true }

# External
async-trait = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["macros", "time", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["io"] }
tracing = { workspace = true }
