[workspace]
resolver = "2"
members = [
    # Application crates
    "crates/db",
    "crates/events",
    "crates/flake-id",
    "crates/join",
    "crates/media",
    "crates/mimetype",
    "crates/models",
    "crates/result",
    "crates/storage",
    "crates/workers",

    # Binary crates
    "server",
]

[workspace.dependencies]
# Workspace crates
db = { path = "crates/db" }
events = { path = "crates/events" }
flake-id = { path = "crates/flake-id" }
join = { path = "crates/join" }
media = { path = "crates/media" }
mimetype = { path = "crates/mimetype" }
models = { path = "crates/models" }
result = { path = "crates/result" }
storage = { path = "crates/storage" }
workers = { path = "crates/workers" }


# External crates
actix-cors = "0.7.1"
actix-multipart = "0.7.2"
actix-web = "4.11.0"
async-trait = "0.1.89"
bytes = "1.11.1"
cassette = { git = "https://github.com/yixone/cassette", branch = "master" }
chrono = "0.4.42"
futures = "0.3.32"
image = { version = "0.25.10", default-features = false }
rand = "0.10.1"
serde = "1.0.219"
sqlx = "0.8.5"
tempfile = "3.27.0"
tokio = "1.47.1"
tokio-util = "0.7.16"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
webp = "0.3.1"
