[workspace]
resolver = "2"
members = [
    # Application crates
    "crates/db",
    "crates/media",
    "crates/models",
    "crates/result",
    "crates/storage",
    "crates/storage_backend",
    "crates/workers",

    # Common crates
    "packages/flake_id",
    "packages/mimetype",

    # Binary crates
    "server",
]

[workspace.dependencies]
# Workspace crates
db = { path = "crates/db" }
media = { path = "crates/media" }
models = { path = "crates/models" }
result = { path = "crates/result" }
storage = { path = "crates/storage" }
storage_backend = { path = "crates/storage_backend" }
workers = { path = "crates/workers" }

flake_id = { path = "packages/flake_id" }
mimetype = { path = "packages/mimetype" }


# External crates
actix-cors = "0.7.1"
actix-multipart = "0.7.2"
actix-web = "4.11.0"
async-trait = "0.1.89"
bytes = "1.11.1"
chrono = "0.4.42"
futures = "0.3.32"
image = "0.25.10"
rand = "0.10.1"
serde = "1.0.219"
sqlx = "0.8.5"
tempfile = "3.27.0"
tokio = "1.47.1"
tokio-util = "0.7.16"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
