[package]
name = "flake-id"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]
sqlx = ["dep:sqlx"]

[dependencies]
# External
chrono = { workspace = true }
rand = { workspace = true }

serde = { workspace = true, features = ["derive"], optional = true }
sqlx = { workspace = true, optional = true }
