[package]
name = "db-sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace
db-core = { workspace = true }

models = { workspace = true, features = ["sqlx"] }
result = { workspace = true }

flake-id = { workspace = true }

# External
async-trait = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "chrono", "runtime-tokio"] }
tracing = { workspace = true }

[dev-dependencies]
db-core = { workspace = true, features = ["tests"] }
tokio = { workspace = true, features = ["macros"] }
