[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace
config = { workspace = true }
db = { workspace = true }
events = { workspace = true }
flake-id = { workspace = true }
instance = { workspace = true }
media = { workspace = true }
mimetype = { workspace = true }
models = { workspace = true, features = ["serde"] }
result = { workspace = true, features = ["actix"] }
storage = { workspace = true }
join = { workspace = true }
telemetry = { workspace = true }
workers = { workspace = true }

# External
actix-cors = { workspace = true }
actix-multipart = { workspace = true }
actix-web = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["io"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
