[package]
name = "jobs"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace
db = { workspace = true }
flake-id = { workspace = true }
media = { workspace = true }
mimetype = { workspace = true }
models = { workspace = true }
result = { workspace = true }
storage = { workspace = true }

# External
async-trait = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["macros", "time", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["io"] }
tracing = { workspace = true }
