[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace
db = { workspace = true }
flake_id = { workspace = true }
media = { workspace = true }
mimetype = { workspace = true }
models = { workspace = true }
storage = { workspace = true }
storage_backend = { workspace = true }

# External
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
